#
###################################
# Site wide configuration
####################################
#
title:       "Carl Ambroselli"
description: "Knowledge base"
url:         # "carl-ambroselli.de" # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Berlin
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Carl Ambroselli
  avatar: avatar.jpg
  job: "IT-Systems Engineering Student"
  bio: "Software Engineer, UI Designer, Snowboarder, wannabe DJ."
  email:
  disqus-shortname: carlambroselli
  twitter: carlambroselli
  facebook: carlambroselli
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: carlambroselli
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: carlambroselli
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
